### ISSUE TITLE
BC after migrating from 2.2.1 to 3.0.0

### ISSUE THREAD

**Issue by carlos-mg89** [doctrine/migrations#1001]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 3.0.0

#### Summary

I'm trying to migrate my current migrations system from 2.2.1 to 3.0.0. I made some changes using the `bin/console make:entity` and right after I ran `bin/console make:migration`, however it keeps running forever without creating the new migration.

It's the first time I'm trying to do this after I've updated the doctrine:migrations package.

#### Previous behavior

Before it took some seconds, and then it generated the migration successfully.

#### More information

This is my old doctrine_migrations.yaml:

```
 doctrine_migrations:
    dir_name: '%kernel.project_dir%/src/Migrations'
    namespace: DoctrineMigrations
    organize_migrations: BY_YEAR_AND_MONTH
```

And this is how I left it, after I got some errors while running the Symfony project for first time, after the package update:

```
doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/src/Migrations'
    organize_migrations: BY_YEAR_AND_MONTH
```

The project works like a charm, however the migratins setup is broken.

I read here https://github.com/doctrine/migrations/issues/967 that I should run `bin/console doctrine:migrations:sync-metadata-storage` in order to have the new migrations v2 setup upgrade to the v3. And apparently everything went fine:
```

vagrant@ubuntu-bionic:/var/www/www.myproject.local$ bin/console doctrine:migrations:sync-metadata-storage

                                                                                                                        
 [OK] Metadata storage synchronized   
```

However, when I ran the make:migration command, this is the result:

```
vagrant@ubuntu-bionic:/var/www/www.myproject.local$ bin/console make:migration

In MetadataStorageError.php line 13:
                                                                                                           
  The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue.  
                                                                                                           

make:migration [--db DB] [--em [EM]] [--shard SHARD] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

And I run again the sync-metadata-storage command, now an errors is thrown:
```

vagrant@ubuntu-bionic:/var/www/www.myproject.local$ bin/console doctrine:migrations:sync-metadata-storage

In MetadataStorageError.php line 13:
                                                                                                           
  The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue.
```

Is there something am I missing? I'm willing to put the needed effort to migration from v2 to v3, since this is a project I've recently started.

Thanks in advance
