### ISSUE TITLE
--db option  not in Doctrine migrations 3 ?

### ISSUE THREAD

**Issue by darkcattz** [doctrine/migrations#1021]
Hello, 

New version of Doctrine migrations no longer has the --db for the command `doctrine:migrations:migrate` option

`[error] Error thrown while running command "crm:createNewDbClient 1". Message: "The "db" argument does not exist."`

How to do now with version 3 of Doctrine Migrations ?

Thanks.

**Comment by goetas** [comment]
to make this feature work with 3.0 we should create a `ConnectionManagerAwareConnectionLoader` (that implements `ConnectionLoader`). and pass that as connection loader to the dependency factory. (Similar to what has been done the the `--config` param in https://github.com/doctrine/migrations/blob/df6138ffd06af43639f73b5b6447bcbe45d289d8/lib/Doctrine/Migrations/Tools/Console/Command/DoctrineCommand.php#L74)

**Comment by darkcattz** [comment]
Thanks. 

the --db option is indeed essential for applications with several databases (in my case more than a hundred, one per customer -> Saas model).
This option allows you to launch Symfony commands with connection on the fly

Regards

**Comment by goetas** [comment]
does your symfony app has defined the connections for all of those customers?

**Comment by goetas** [comment]
@darkcattz Can you please explain a bit more in detail how are you using this feature? We had a team discussion on how to re-implement this in 3.0 and we wanted to see if there are ways to improve it (as example allowing to run migrations across all defined connections...?)

**Comment by darkcattz** [comment]
No, only 2 connections :
- One for the factory (customer list : each line describes the client + the (random) name of his database
- Another default connection which serves as the basis for the connection but which I must complete with the correct client base name to connect to its database.

E.g. : Symfony crm:createNewCustomerDatabase command :
1°) I check that the user has been created in the factory and I get the name of its random database name (which does not yet exist)
2°) I create a new Mysql user for this customer with only the rights on his database (Doctrine Dbal).
3°) I create the client's database (empty for now)
4°) I launch the Doctrine Migrations command with the --db option which will directly create all the tables in the new client database and hydrate important tables (creation of default users for example).
5°) The client base is now operational and the client can connect to the application (checking the client's name in the factory and changing the Doctrine connection on the fly at each login with the correct credentials).

E.g. for doctrine migrations : 
`
                    $reflectionConn = new \ReflectionObject($this->doctrine->getConnection('factory'));
                    $reflectionParams = $reflectionConn->getProperty('params');
                    $reflectionParams->setAccessible(true);

                    $params = $reflectionParams->getValue($this->doctrine->getConnection('factory'));
                    $params['dbname'] = $clientDatabase;

                    $reflectionParams->setValue($this->doctrine->getConnection('factory'), $params);
                    $reflectionParams->setAccessible(false);

                    //Run Doctrine Migrations to create tables in customer database : 
                    $command = $this->getApplication()->find('doctrine:migrations:migrate');
                    $arguments = [
                        'command' => 'doctrine:migrations:migrate',
                        '--db'  => 'factory',
                    ];
                    $databaseCreateInput = new ArrayInput($arguments);
                    $databaseCreateInput->setInteractive(false);
                    $returnCode = $command->run($databaseCreateInput, $output);

                    $io->title("\r\nMigrations - doctrine:migrations.migrate : OK");`

**Comment by AndyDune** [comment]
It is very bad --db option was removed.
In my local machine I hav 2 DBs: to almost real db and test.
And from now I can't use migration for test db.

Это просто пиздец!

**Comment by goetas** [comment]
see https://github.com/doctrine/migrations/pull/1023

**Comment by alexgit2k** [comment]
> Can you please explain a bit more in detail how are you using this feature? We had a team discussion on how to re-implement this in 3.0 and we wanted to see if there are ways to improve it (as example allowing to run migrations across all defined connections...?)

@goetas We are using --db to supply a database-user with extended permissions like creating, dropping, altering tables for executing migrations whereas the ordinary user for running the application has only select, insert- and update-permissions.

**Comment by goetas** [comment]
@alexgit2k how do you distinguish which migrations run under one connection to the one that runs under the privileged connection?

**Comment by alexgit2k** [comment]
@goetas ALL migrations are executed under the privileged connection during deployment. The ordinary user is not used for migrations, only for running the application.

**Comment by goetas** [comment]
@alexgit2k  that is already possible. You probably have a config as this:

```yml
# packages/doctrine.yml
doctrine:
    dbal:
        default_connection:           default
        connections:
            default:
                dbname:               ~
                host:                 localhost
                user:                 root
                password:             ~
          privileged:
                dbname:               ~
                host:                 localhost
                user:                 root
                password:             ~
```
You can define 

```yml
# packages/prod/doctrine_migrations.yml
doctrine_migrations:
    connection: dbname
```

In this way on production the migrations will use the privileged connection.

**Comment by cmelius** [comment]
ok, works!  Thank you. 

This should be in the upgrade to 3.0 document!
https://github.com/doctrine/migrations/blob/master/UPGRADE.md#upgrade-to-30

**Comment by goetas** [comment]
implemented in https://github.com/doctrine/migrations/pull/1023

**Comment by darkcattz** [comment]
Hello, 

I tried the new "--conn" option command on version 3.1 but it still tries to connect to the default database.

Command :  console doctrine:migrations:migrate --conn="factory"

Error : 
SQLSTATE[HY000] [1045] Access denied for user 'user-account'@'planisphere_php_1.planisphere_default' (using passw
  ord: YES)

Normally the user for the factory is 'root', not 'user-account'.
user-account is default-user for the default connection.

I tried this solution to force privileged connection : Same result. 

```
# packages/prod/doctrine_migrations.yml
doctrine_migrations:
    connection: factory
```

An idea ?

Thanks

**Comment by darkcattz** [comment]
same problem with : console doctrine:migrations:migrate --conn=factory

**Comment by kuzinmv** [comment]
> same problem with : console doctrine:migrations:migrate --conn=factory

You can try to do the next trick for v 3.0, 3.1 & Symfony

Overwrite 1 argument to `null` for the `doctrine_migrations.migrate_command` in your services.yml
```
  doctrine_migrations.migrate_command:
        class: Doctrine\Migrations\Tools\Console\Command\MigrateCommand
        arguments: [null, 'doctrine:migrations:migrate']
        tags:
            -  name: 'console.command'
               command: 'doctrine:migrations:migrate'
```

After that, your command start correctly process `--configuration` and `--db-configuration` options from the command line

```
php bin/console doctrine:migrations:migrate next -n --configuration=config/extra/doctrine/migrations-config.yml --db-configuration=config/extra/doctrine/migrations-db.php
```

my example of migrations-config.yml 
```
migrations_paths:
  'DoctrineMigrations\DefaultDatabase': 'migrations/default'
table_storage:
  table_name: 'migration_versions'
  version_column_name: 'version'
  version_column_length: 191
  executed_at_column_name: 'executed_at'
organize_migrations: year_and_month
all_or_nothing: false
custom_template: config/extra/doctrine/migrations_template_sharding.thp
```

Keep in mind that manually configuration is different a little bit from `config/packages/doctrine_migrations.yaml`
you can not use `%kernel.project_dir%` or special constant `BY_YEAR_AND_MONTH`


Connection configuration example migrations-db.php

```
<?php
global $kernel;
return $kernel->getContainer()->get("doctrine.dbal.{$_ENV['WHOAMI']}_connection");

```
And now you can use .ENV  variable to select connection by its name in runtime

```
WHOAMI=db_instance_3 php bin/console doctrine:migrations:migrate next -n --configuration=config/extra/doctrine/migrations-config.yml --db-configuration=config/extra/doctrine/migrations-db.php
```

```
 >> 2020-07-02 06:00:27 (20200701125523)
[notice] Migrating up to DoctrineMigrations\DefaultDatabase\Version20201125072328
[notice] finished in 239.7ms, used 26M memory, 1 migrations executed, 1 sql queries
```
