### ISSUE TITLE
Using replicas config

### ISSUE THREAD

**Issue by AlexZodov** [doctrine/migrations#1155]
|    Q        |   A
|------------ | -----
| Version     | 3.1.2

 Other packages versions: 
doctrine/dbal 2.13.1 
doctrine/migrations 3.1.2 
doctrine/doctrine-migrations-bundle 3.1.1 
doctrine/bundle 2.3.1

### Support Question

My config looks like that:

```
doctrine:
    dbal:
        default_connection: diary
        connections:
            shop:
                url: '%env(resolve:SHOP_DATABASE_URL_MASTER)%'
                options:
                    1002: 'SET sql_mode=(SELECT REPLACE(@@sql_mode, "ONLY_FULL_GROUP_BY", ""))'
                replicas:
                    replica1:
                        url: '%env(resolve:SHOP_DATABASE_URL_SLAVE)%'
                    replica2:
                        url: '%env(resolve:SHOP_DATABASE_URL_MASTER)%' 
```

and I`m getting error

```
In PrimaryReadReplicaConnection.php line 140:
  Passing a connection name as first argument is not supported anymore. Use ensureConnectedToPrimary()/ensureConnectedToReplica() instead. 
```

on each try of command `doctrine:migrations:diff --em=shop_em` or `doctrine:migrations:diff`
