### ISSUE TITLE
Alternative connection via --conn option is ignored

### ISSUE THREAD

**Issue by alexgit2k** [doctrine/migrations#1160]
#### Summary

In #1023 the option to allow alternative connections via --conn option was added. However as also stated in https://github.com/doctrine/migrations/issues/1062#issuecomment-801171576 and https://github.com/doctrine/migrations/issues/1062#issuecomment-807348508 an alternative connection specified via --conn option is ignored and the default connection is used instead.

#### Current behavior

Default connection is used.

#### How to reproduce

```
bin/console doctrine:migrations:migrate --dry-run -vvv --no-interaction --conn=migrations
```

```
doctrine:
    dbal:
        default_connection: default
        # configure these for your database server
        connections:
            default:
                url: '...'
            migrations:
                url: '...'
```

#### Expected behavior

Alternative connection should be used.

**Comment by goetas** [comment]
can you please tell us which version of the doctrine migrations bundle are you using?

**Comment by alexgit2k** [comment]
@goetas: of course the latest release:
```
$ ./vendor/bin/doctrine-migrations -v
Doctrine Migrations 3.1.2@1c2780df6b58998f411e64973cfa464ba0a06e00
```

**Comment by dant89** [comment]
Experiencing the same issue with:

```
php bin/doctrine-migrations -v
Doctrine Migrations 3.1.0@260991be753a38aa25b6f2d13dbb7f113f8dbf8f
```

**Comment by goetas** [comment]
> can you please tell us which version of the doctrine migrations bundle are you using?

Are you using the symfony bundle? if yes, what is the bundle version (not the migrations lib)

**Comment by ureimers** [comment]
Hi,
as I have the same problem (stated in https://github.com/doctrine/migrations/issues/1062#issuecomment-801171576), I switched to the DEV branch of the migrations bundle, just to be sure not to miss any unreleased fix to this:

```
doctrine/doctrine-migrations-bundle      3.2.x-dev fda5e69
doctrine/migrations                      3.2.0
```

It doesn't matter what is defined as the `--conn` parameter, it seems to be simply ignored:

```
bin/console doctrine:migrations:migrate -n --conn=this-connection-does-not-exist

 [OK] Already at the latest version ("DoctrineMigrations\Version20210727091159")

```

**Comment by goetas** [comment]
@ureimers hmm. that is weird and looks like a big :(

**Comment by goetas** [comment]
So, after looking into the issue, there is a problem when there is only the default entity manager... the --conn option is ignore and always the entity manager connection is choosen.

could you share your doctrine migrations and doctrine connection configs?

**Comment by ureimers** [comment]
Hi @goetas,
I was away for a month, so please excuse the late response. Here are my configurations (I removed some internal bundle names):

```
# doctrine.yaml

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                charset: UTF8
            live:
                url: '%env(resolve:LIVE_DATABASE_URL)%'
                charset: UTF8
            user:
                url: '%env(resolve:USER_DATABASE_URL)%'
                charset: UTF8
            live_user:
                url: '%env(resolve:LIVE_USER_DATABASE_URL)%'
                charset: UTF8
            log:
                url: '%env(resolve:DATABASE_URL)%'
                charset: UTF8

    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers:
            default: &doctrine_default_entity_manager
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    # [...] lots of custom bundles
                    FOSUserBundle: ~
                    SonataUserBundle: ~
                dql:
                    numeric_functions:
                    # [...] some DQL functions
            live:
                <<: *doctrine_default_entity_manager
                connection: live

            user:
                <<: *doctrine_default_entity_manager
                connection: user
```

```
# doctrine_migrations.yaml

doctrine_migrations:
    services:
        'Doctrine\Migrations\Version\MigrationFactory': 'App\Migrations\MigrationFactoryDecorator'
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
```

**Comment by goetas** [comment]
hmm, that seems weird. is there a way to reproduce this somehow in a failing test case?

**Comment by feosys** [comment]
has it already been fixed?

**Comment by goetas** [comment]
> has it already been fixed?

you did not mange to reproduce it? or you saw a commit fixing it?

**Comment by mussbach** [comment]
I face the same issue and you seem to be right:
> So, after looking into the issue, there is a problem when there is only the default entity manager... the --conn option is ignore and always the entity manager connection is choosen.

This is the case for us as well. 
As I am not very familiar with the code: Where do you suggest to locate the Test?

**Comment by goetas** [comment]
@mussbach so you have one entity manager and multiple connections, right?

and commands and `diff` will need to the entity manager, while the commands as `migrate` will need to choose on which connection to run.

So my question is: why do you have two connections if you have only one entity manager? what is doing the other connection?

**Comment by mussbach** [comment]
Yes, you understood it correctly. 
Our usecase is that we have a privileged user with alter (and some more) rights that we want to use only during migration to keep the permission set for the „ordinary“ user as small as possible.
Both users need the same entities to be managed.

**Comment by Kleinast** [comment]
I tried to update from 2.x to 3.4 and have the same error with multiple connection.
Is there a workaround or a commit who fix it ?

Thx in advance

**Comment by schodemeiss** [comment]
I have the same issue. I have 2 connections, lets say "default" and "database_2" *but* only one Entity Manager on "default" (my second connection doesn't need Entities.

If I provide "--conn database_2" to any of the migration commands, it always falls back to the "default".

Any ideas how to sort this?

**Comment by ToGoLimango** [comment]
i could solve this for me by adding "connection: migrations to doctrine_migrations.yaml (or the connection you need than)

so at the end its looking like this:

```
doctrine_migrations:
    connection: migrations
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
```

**Comment by kSHerstyanikov** [comment]
has it already been fixed?

**Comment by revilon1991** [comment]
While we are waiting for the fix we can use flag `--em` instadeof `--conn`.
Just don't forget to [configure an enity manager](https://symfony.com/doc/current/doctrine/multiple_entity_managers.html) and set nessasary connection.
```yaml
# config/packages/doctrine.yaml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                # ...
            migrations: # <--- connection for migration
                url: '%env(resolve:DATABASE_MIGRATIONS_URL)%'
                # ...
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                # ...
            migrations: # <--- orm manager for connection
                connection: migrations
                # ...
```
and run
```bash
php bin/console doctrine:migrations:migrate --no-interaction --em=migrations
```
