### ISSUE TITLE
generating new migrations creates the same junk in the down() method every time

### ISSUE THREAD

**Issue by arderyp** [doctrine/migrations#1240]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | i don't know
| Version     | 3.4.1 (doctrine-migrations-bundle 3.2.1)

#### Current behavior

Firstly, it used to be the case that `./bin/console doctrine:migrations:diff` would not generate anything if the database schema was in sync.  I am not sure if perhaps that behavior was changed, but in my current state running this command always generates a migrations file.  I can run it 10 times in a row and it will create 10 migrations files with blank `up()` method bodies.

Secondly, every time I generate a migration file, it always includes the same spam in the `down()` method. I've run multiple generated migration files since this behavior started, and its continues to persist (running migrations shouldn't fix the problem anyway, as this is a problem in the `down()` method, not `up()`.

Here is an example of the spam:

```
public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE table_one CHANGE description description LONGTEXT CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE name name VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`, CHANGE short short VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`');
        $this->addSql('ALTER TABLE table_two CHANGE type type VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_general_ci`');
        ....
    }
```
There are dozens of `addSql()` statements, I've just included a few for brevity.  They all follow this same pattern related to `utf8` and `utf8_general_ci`.

#### How to reproduce

I don't know specific steps, this is happening every time I generate a migration file, the same spam in `down()` each time.

**Comment by arderyp** [comment]
P.S. if there are any steps you want me to take, or info I can provide to further assist, please let me know, I'm happy to test.

**Comment by Flo354** [comment]
Hello there,

We are encountering the same problem. 
Downgrade to version 3.3.2 fix the problem, for now...

**Comment by apfelbox** [comment]
I have the same issue, but for both `up` and `down` migrations..

**Comment by greg0ire** [comment]
Do you have similar issues with `doctrine:schema:update`? Is this related to https://github.com/doctrine/DoctrineBundle/issues/1468 ?

**Comment by arderyp** [comment]
@greg0ire I don't think I've every run `doctrine:schema:update`, so I am not sure

@apfelbox after upgrading from doctrine 3.3.x to 3.4.x my `doctrine:schema:valida` was no longer passing. I generated `doctrine:migrations:diff` and it included a handful of migration statement in the `up()` method, but they seemed reasonable, and like they reflected a change in doctrine(migrations) handling of specific text field declarations.   I executed the migration just fine, and now when I run `doctrine:migrations:diff` the `up()` method is empty, but I still keep getting this junk in `down()`.  Do you keep getting the same junk in `up()`, even after you execute that generated `up()` migration?

**Comment by Flo354** [comment]
@arderyp I get the exact same behavior as yours. First, a bunch of useless changes in `up` and `down`. I executed the `up` by manually removing the useless part. 

Now, no more useless in `up`, but the same on `down` at every `diff`.

Same behavior in versions 3.4.0 and 3.4.1
I reverted to 3.3.2

**Comment by greg0ire** [comment]
If the contents of `up()` go away after a few tries, then it's probably more subtle than it is useless… Nevermind my question about `doctrine:schema:update`, since it's equivalent to `up()`, and the issue seems to be with `down()`.

I'm not an expert with this package, but what I know is that it relies on `doctrine/dbal` to generate the diff.
It would be great to locate the bug first, because right now, this seems to have been reported to
- `doctrine/migrations-bundle`: https://github.com/doctrine/DoctrineMigrationsBundle/issues/470
- `doctrine/migrations`
- `doctrine/doctrine-bundle`: https://github.com/doctrine/DoctrineBundle/issues/1468
- `doctrine/dbal`: https://github.com/doctrine/dbal/issues/5265

I'm bracing for a report on `doctrine/orm`.

It could be useful to debug this piece of code: https://github.com/doctrine/migrations/blob/e7df670aa9565b435ffec636cebdb4d0a1987f10/lib/Doctrine/Migrations/Generator/DiffGenerator.php#L103-L123, to see if maybe `$fromSchema` or `$toSchema` look wrong. Intuitively, I think the issue would be with `doctrine/dbal` because it's not symmetrical (the issue is with `down()` only).

If you can reproduce the issue with only the DBAL, by calling https://github.com/doctrine/migrations/blob/e7df670aa9565b435ffec636cebdb4d0a1987f10/lib/Doctrine/Migrations/Generator/DiffGenerator.php#L115

with 2 schema objects you create "manually" that would be really helpful.

**Comment by arderyp** [comment]
yeah I am not sure my `up()` generation was useless, it seemed reasonable enough.

very helpful compilation of info @greg0ire. And apologies in advance if I opened this on the wrong repo.  My google-fu didn't lead me to those other issues.

I will try following your suggested debugging approach next week and report back.

**Comment by greg0ire** [comment]
Okay. Note that somebody else confirmed tonight that https://github.com/doctrine/DoctrineBundle/pull/1471 might fix this

**Comment by arderyp** [comment]
Awesome news @greg0ire !

So we are just waiting on 2.5.6 release of DoctrineBundle to resolve this, is that right?

Thanks again.

**Comment by floviolleau** [comment]
Hi,

I updated to latest and I still have the issue.
If I don't configure anything in doctrine.yml, I still have a migration generated in down() function.

```yaml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(DATABASE_URL)%'
                server_version: 5.7
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Translatable/Entity"
                        alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
                        is_bundle: false
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
            tracabilite:
                connection: tracabilite
```

```bash
Restricting packages listed in "symfony/symfony" to "5.4.*"
Updating dependencies
Lock file operations: 0 installs, 9 updates, 0 removals
  - Upgrading doctrine/dbal (3.3.0 => 3.3.2)
  - Upgrading doctrine/doctrine-bundle (2.5.5 => 2.5.6)
  - Upgrading phar-io/version (3.1.0 => 3.1.1)
  - Upgrading psalm/plugin-symfony (v3.1.2 => v3.1.3)
  - Upgrading react/promise (v2.8.0 => v2.9.0)
  - Upgrading sebastian/global-state (5.0.3 => 5.0.5)
  - Upgrading symfony/webpack-encore-bundle (v1.13.2 => v1.14.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 10 updates, 0 removals
  - Downloading composer/package-versions-deprecated (1.11.99.1)
  - Downloading doctrine/dbal (3.3.2)
  - Downloading doctrine/doctrine-bundle (2.5.6)
Gathering patches for root package.
Gathering patches for dependencies. This might take a minute.
  - Downgrading composer/package-versions-deprecated (1.11.99.5 => 1.11.99.1): Extracting archive
  - Upgrading doctrine/dbal (3.3.0 => 3.3.2): Extracting archive
  - Upgrading doctrine/doctrine-bundle (2.5.5 => 2.5.6): Extracting archive
  - Upgrading react/promise (v2.8.0 => v2.9.0): Extracting archive
  - Upgrading sebastian/global-state (5.0.3 => 5.0.5): Extracting archive
  - Upgrading phar-io/version (3.1.0 => 3.1.1): Extracting archive
  - Upgrading psalm/plugin-symfony (v3.1.2 => v3.1.3): Extracting archive
  - Upgrading symfony/webpack-encore-bundle (v1.13.2 => v1.14.0): Extracting archive
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Package webmozart/path-util is abandoned, you should avoid using it. Use symfony/filesystem instead.
```

Any ideas?
Thanks
