### ISSUE TITLE
MSSQL migration:diff so much queries execute to system checks

### ISSUE THREAD

**Issue by alexgrupapunts** [doctrine/migrations#1268]
There are more a question than a problem detected or maybe bad configuration of project with Symfony. 

I'm working with MSSQL database version 11.0.2100.60 with 3 different connections on the same project, when i execute some command for schema update or migration diff this actions take long time to finish last time (20 minutes) and when i look at 'var/log/dev.log' here have more than 4000 lines of queries that process used to finish (At the end i paste my actual doctrine.yaml config).

Another one have the same problem or know what im doing in bad way?¿

|    Q        |   A
|------------ | -----
| Version     | x.y.z
| doctrine/doctrine-migrations-bundle  |  3.2.2
| doctrine/orm | 2.11.0
| doctrine/dbal | 2.13.7
| symfony | 6.1.3

```
doctrine:
    dbal:
        default_connection: default
        #override_url: true
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
            log:
                url: '%env(resolve:DATABASE_LOGS_URL)%'
            a3:
                url: '%env(resolve:DATABASE_URL_A3)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/DBCRM'
                        prefix: 'App\Entity'
                        alias: App
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
                dql:
                    string_functions:
                        CAST: DoctrineExtensions\Query\Mysql\Cast
                        COLLATE: App\DQL\MSSQL\Collate
            log:
                connection: log
                auto_mapping: false
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
            a3:
                connection: a3
                auto_mapping: false
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    App:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/DBA3'
                        prefix: 'App\Entity\DBA3'
                        alias: A3
```
