### ISSUE TITLE
Unable to create migration version table within non-default schema

### ISSUE THREAD

**Issue by thsmrtone1** [doctrine/migrations#1321]
DB platform: MSSQL (sqlsrv)

Using the following config:

```yaml
doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    storage:
        table_storage:
            table_name: 'alt_schema.MigrationVersions'
```

The first time I execute the migration, it will successfully run, and will automatically create the MigrationVersions table within the alt_schema schema. However, on subsequent migrations, I will receive the following error:

```
An exception occurred while executing a query: SQLSTATE [42S01, 2714]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]There is already an object named 'MigrationVersions' in the database.
```
