### ISSUE TITLE
Status detection broken after upgrade from 2.3.4 to 3.5.5

### ISSUE THREAD

**Issue by Herz3h** [doctrine/migrations#1347]
### BC Break Report

I upgraded from doctrine/migrations 2.3.4 to 3.5.5 breaks migrations detections

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 3.5.5

#### Summary

Introduction of `migration_paths` breaks detection of executed migrations. 

Before upgrade, I had this configuration (yaml):

```yaml
doctrine_migrations:
    dir_name: "%kernel.project_dir%/src/Migrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations
    organize_migrations: false 
```

After upgrade:
```yaml
doctrine_migrations:
    migrations_paths:
      'Application\Migrations': '%kernel.project_dir%/src/Migrations'
    organize_migrations: false
    storage:
      table_storage:
        table_name: migration_versions
```

#### Previous behavior

Running doctrine:migration:status previously reported migrations as executed.

#### Current behavior

Running doctrine:migration:status now, shows that all my migrations are not executed. 

#### How to reproduce

Install migration v2.3.4, execute some migrations then upgrade to v3.5.5.

Upon digging, it seems the problem is upon using ReflectionClass, getName returns the FQDN of the class instead of the short class name (maybe it used to do this before?):

https://github.com/doctrine/migrations/blob/832ef284bb12bb896202d887cc45db22d104a2ce/lib/Doctrine/Migrations/Finder/Finder.php#L63

Added screenshot of migration_versions table:

<img width="614" alt="image" src="https://github.com/doctrine/migrations/assets/1900696/0f20db80-290b-4476-b2ee-12d9be176f1e">

Because afterwards it is comparing executed version name vs available version, but they dont match, one has FQDN while in the DB it says Version2023... only without namespace.

<img width="636" alt="image" src="https://github.com/doctrine/migrations/assets/1900696/1bbd44ae-ffcc-4822-91e3-640b2057ff01">

**Edit**: Found the commit that changed the behavior (3.0 release commit):
https://github.com/doctrine/migrations/commit/d74785fd5a21d7f7fa2d04f61427c11169cb0ce2#diff-3ba1cb4b1d3fc85dc36972850335e25c1e714e8dad9f794a0ff79ec7b2a2ec94L67
