### ISSUE TITLE
Missing to generate the column for one ManyToOne Relationship

### ISSUE THREAD

**Issue by Raffaello** [doctrine/migrations#255]
[Maybe it could be related to DoctrineMigrationBundle]

I think it is a particular case, I try to explain and make it reproducible:

I did 2 migration for a new entity in 2 differnt period of time, I don't know it could be trigger the issue but what I did it exaclty the things reported here.

1. Create the new entity with 1 ManyToOne relationship (everything was fine)
2. Update the new entity removed a unique index and a column type string and added (substitute) with another ManyToOne relationship to another new Entity. (In this case the diff command cannot generate the new column to mapping the new relationship) 
I succesfully be able to make the generation of this new column renaming adn moving the previos ManyToOne relationship (in step 1).

here my mapping to help reproduce the code (update were required to make them complete):

1. in the first step (so a migration itself) the entity was:
```
    Entity\RemoteUser:
        type: entity
        table: remoteusers
        repositoryClass: RemoteUserRepository
        #indexes:
        manyToOne:
            contact:
                targetEntity: Contact
                joinColumn:
                    name: remoteuser_contact_id
                    referencedColumnName: contact_id
                    nullable: false
        fields:
            id:
                id: true
                type: integer
                #nullable: false
                #id: true
                column: remoteuser_id
                generator:
                    strategy: IDENTITY

            authType:
                type: string
                length: 255
                nullable: false
                column: remoteuser_authtype

            username:
                type: string
                length: 255
                nullable: false
                column: remoteuser_username

        uniqueConstraints:
            uniqueConstraint:
                name: remoteuser_authtypeusername_unique
                columns: [remoteuser_authtype, remoteuser_username]

        #lifecycleCallbacks: {  }
```

in the sencod step this entity is updated with (removed the authType columnd and unique index and added the many-1 rel to another table):
```
    RemoteUser:
        type: entity
        table: remoteusers
        repositoryClass: RemoteUserRepository
        #indexes:
        manyToOne:
            contact:
                targetEntity: Contact
                joinColumn:
                    name: remoteuser_contact_id
                    referencedColumnName: contact_id
                    nullable: false
        manyToOne:
            authorization:
                targetEntity: RemoteUserAuthorization
                joinColumn:
                    name: remoteuser_authorization_id
                    referencedColumnName: remoteuserauthorization_id
                    nullable: false
        fields:    
            id:
                id: true
                type: integer
                #nullable: false
                #id: true
                column: remoteuser_id
                generator:
                    strategy: IDENTITY

            username:
                type: string
                length: 255
                nullable: false
                column: remoteuser_username
    
        #lifecycleCallbacks: {  }
```

Doctrine migration diff command cannot generate correctly the new mapping, In my case it missing to generate the column remoteuser_authorization_id 

If I rename the first ManyToOne rel.( the contact one) It will generate correctly everything.
UPDATED: honestly The first ManyToOne relationship I have moved below the new one and renamed the column name (code updated as well)
So, I am guessing that there is a bug, that make the diff command to skip a new many to one relathionship because it match something already present, but it is not exhaustive in its search.
[below the working mapping].

```
    RemoteUser:
        type: entity
        table: remoteusers
        repositoryClass: RemoteUserRepository
        #indexes:
        manyToOne:
            authorization:
                targetEntity: RemoteUserAuthorization
                joinColumn:
                    name: remoteuser_authorization_id
                    referencedColumnName: remoteuserauthorization_id
                    nullable: false
        manyToOne:
            contact:
                targetEntity: Contact
                joinColumn:
                    name: remoteuser_contact_id2
                    referencedColumnName: contact_id
                    nullable: false
        fields:    
            id:
                id: true
                type: integer
                #nullable: false
                #id: true
                column: remoteuser_id
                generator:
                    strategy: IDENTITY

            username:
                type: string
                length: 255
                nullable: false
                column: remoteuser_username
    
        #lifecycleCallbacks: {  }
```
