### ISSUE TITLE
migration bundle's directory placeholders are throwing an error

### ISSUE THREAD

**Issue by Myke79** [doctrine/migrations#264]
Somewhere since 1dab0785ddbf61749918d0097f7032ec5071f18c, the doctrine migration bundle's directory placeholders are throwing an error.
For example when I call:
```
doctrine:migrations:status --configuration=/path/to/the/migrations.yml --show-versions
```
migrations.yml:
```yaml
name: Doctrine DimworksBackendBundle Migrations
migrations_namespace: Dimworks\BackendBundle\Migrations
table_name: cms_migration_versions
migrations_directory: %kernel.root_dir%/../vendor/dimworks/backendbundle/src/Dimworks/BackendBundle/DoctrineMigrations
```
it's now throws an error:
```
[InvalidArgumentException]
Cannot load migrations from "%kernel.root_dir%/../vendor/dimworks/backendbundle/src/Dimworks/BackendBundle/DoctrineMigrations" because it is not a valid directory 
```
Maybe it's tries to process the migrations_directory before the migrations bundle replace it's placeholders.

I don't know where it should be fixed. Here or the migration bundle's side.
But I post it here, because something changed this side.
