### ISSUE TITLE
Support custom template in diff command

### ISSUE THREAD

**Issue by alcaeus** [doctrine/migrations#566]
#535 add support for changing the class template, but it's only used for the `generate` command, not for `diff`.

**Comment by enumag** [comment]
There is one more issue with the custom templates that I'd like to have fixed in 1.6. When I use doctrine-migrations-bundle and configure it like this:

```
doctrine_migrations:
    dir_name: '%kernel.project_dir%/src/Core/Infrastructure/Doctrine/Version'
    namespace: App\Core\Infrastructure\Doctrine\Version
    table_name: _db_version
    name: Application Migrations
    organize_migrations: BY_YEAR_AND_MONTH
    custom_template: '%kernel.project_dir%/src/Library/Resource/migration.tpl'
```

Then it fails with this exception:

```
  [InvalidArgumentException]                                                                                                   
  The specified template "/home/enumag/Projects/foobar/src/Library/Resource/migration.tpl" cannot be found or is not readable.  
```

The reason is that the command always [prepends](https://github.com/doctrine/migrations/blob/master/lib/Doctrine/DBAL/Migrations/Tools/Console/Command/GenerateCommand.php#L131) the current working directory. It should only do so if the path is relative but not when it's absolute.
