### ISSUE TITLE
Problem with doctrine diff

### ISSUE THREAD

**Issue by GuigZ-** [doctrine/migrations#598]
Hi,

When i use the doctrine diff, doctrine create a file with this line : 

```php
<?php declare(strict_types = 1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20180129135625 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE address CHANGE complement complement VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE address CHANGE complement complement VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8_unicode_ci');
    }
}
```

**Comment by chrisguitarguy** [comment]
@GuigZ- we'll need some more info about what you expected vs what happened.

But, in general, problems with the database diffing are bugs in [`doctrine/dbal`](https://github.com/doctrine/dbal) not migrations.

**Comment by stof** [comment]
This should be reported to doctrine/dbal, as it is the project implementing the schema diffing (the migrations project rely on the schema diffing tools of DBAL).

Btw, when reporting it to DBAL, please provide more information about your schema and about the platform you are using.

**Comment by GuigZ-** [comment]
I use Symfony 4, with php 7 and MariaDB from latest version.

My mapping is 
```yml
App\Entity\Address:
  type: entity
  repositoryClass: App\Repository\AddressRepository
  indexes:
    uuid_index:
      columns: [ uuid ]
  id:
    id:
      type: integer
      generator: {strategy: AUTO}
  fields:
    uuid:
      type: uuid
      unique: true
    name:
      type: string
      length: 100
    address:
      type: string
      length: 255
    complement:
      type: string
      nullable: true
      length: 255
    postcode:
      type: string
      length: 100
    city:
      type: string
      length: 100
    deleted:
      type: boolean
    createdAt:
      type: datetime
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      gedmo:
        timestampable:
          on: update
```
