### ISSUE TITLE
Bad column type used by SQL generator for MSSQL

### ISSUE THREAD

**Issue by macintoshplus** [doctrine/migrations#753]
### Bug Report

I use Doctrine ORM and Doctrine Mibration Bundle in my Symfony 4 project. The mapping configuration is written in YAML and i generate the migration class by this command: `bin/console doctrine:migration:diff`.

For MariaDB, no error, but for MS SQL, two collumn type used are wrong.

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | 1.8.1

#### Summary

This is a part of my entity configuration:

```
App\Entity\EntityName:
    type: entity
    table: entity_name
    options:
        charset: utf8mb4
        collate: utf8mb4_general_ci
    id:
        entityid:
            type: string
            length: 36
            id: true
    fields:
        updatedAt:
            type: datetime
            nullable: true
        metadatas:
            type: text
            nullable: true
    lifecycleCallbacks: {  }
```

#### Current behavior

The generated SQL is:

``` php
$this->addSql('CREATE TABLE entity_name (entityid NVARCHAR(36) NOT NULL,  updated_at DATETIME,  metadatas VARCHAR(MAX), PRIMARY KEY (entityid))');
```

The `entityid` type is true, but the `updated_at` is wrong, the type must be `DATETIME2` instead `DATETIME`, and for `metadatas` the type is also wrong. The type must be `NVARCHAR(max)` instead `VARCHAR(max)`.

#### Expected behavior

The expected SQL:

``` php
$this->addSql('CREATE TABLE entity_name (entityid NVARCHAR(36) NOT NULL,  updated_at DATETIME2,  metadatas NVARCHAR(MAX), PRIMARY KEY (entityid))');
```
