### ISSUE TITLE
dir_name does not support multiple directories

### ISSUE THREAD

**Issue by precious-coder** [doctrine/migrations#805]
I want to use https://github.com/doctrine/migrations/pull/238 because I've migrations in my current Symfony project and in a shared bundle which sits in `/vendor`. 

```yaml
doctrine_migrations:
    dir_name:
        - '%kernel.project_dir%/src/Migrations'
        - '%kernel.project_dir%/vendor/precious/very-barebone/src/Migrations'
    # namespace is arbitrary but should be different from App\Migrations
    # as migrations classes should NOT be autoloaded
    namespace: DoctrineMigrations
```
Does not work:
> Invalid type for path "doctrine_migrations.dir_name". Expected scalar, but got array.

**Comment by jschaedl** [comment]
The implementation in #238 allows to have several subfolders in your configured doctrine migrations directory. But it is not possible to have several directories including migration files in different places.

I suggest you separate the doctrine migrations configuration for your application and your shared bundle. So you can execute them separately by providing the proper configuration file with the `--configuration` option:

```yaml
# doctrine_migrations_app.yaml

doctrine_migrations:
    dir_name:
        - '%kernel.project_dir%/src/Migrations'
    namespace: DoctrineMigrations
```

```yaml
# doctrine_migrations_very-barebone.yaml

doctrine_migrations:
    dir_name:
        - '%kernel.project_dir%/vendor/precious/very-barebone/src/Migrations'
    namespace: DoctrineMigrations
```

Now you can execute migrations separately:
- `./bin/doctrine migrations:migrate --configuration='doctrine_migrations_app.yaml'`
- `./bin/doctrine migrations:migrate --configuration='doctrine_migrations_very-barebone.yaml'`
