### ISSUE TITLE
Indexes and uniqueConstraints has been ignored

### ISSUE THREAD

**Issue by diegoholiveira** [doctrine/migrations#98]
I declared my entity with the indexes section, like this:

``` yaml
indexes:
        IDX_ADDRESS_CITY:
            columns: city_id
```

but, the Diff tools ignore it and give me this code:
`$this->addSql("CREATE INDEX IDX_7299B5238BAC62AF ON tb_address (city_id)");`

 and it should be:
`$this->addSql("CREATE INDEX IDX_ADDRESS_CITY ON tb_address (city_id)");`
