### ISSUE TITLE
entries in the migrations table are not automatically updated

### ISSUE THREAD

**Issue by vladyslavstartsev** [doctrine/migrations#991]
|    Q        |   A
|------------ | -----
| Version     | 3.0.0

### Support Question

Hi!
I'm migrating from version 2 to 3
In update notes is says that 
```
The "version" is the FQCN of the migration class (existing entries in the migrations table will be automatically updated).
``` 

but I have working app with filled migrations table (the old one). How do I actually `automatically update`? 
Right now I, if I do `./console doctrine:migrations:migrate`, it tries to execute all the migrations from the beginning

**Comment by vladyslavstartsev** [comment]
Oh, there is one more BC break not covered by docs

before update the default `table_name` was
```yaml
    table_name: 'migration_versions'
```

after update it's 
```yaml
    table_name: 'doctrine_migration_versions'
```

I have to set it explicitly to work correctly

**Comment by goetas** [comment]
more info about this in https://github.com/doctrine/DoctrineMigrationsBundle/pull/340

**Comment by raress96** [comment]
Hello. I have been trying to update Doctrine Migrations 2 to 3, but I still have this issue...

I have the following in my configuration:

```
doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/src/Migrations'
    storage:
        table_storage:
            table_name: 'migration_versions'
            version_column_name: 'version'
            version_column_length: 191
            executed_at_column_name: 'executed_at'
            execution_time_column_name: 'execution_time'
```

I have the following output in `doctrine:migrations:status` command:
![Screenshot 2023-03-08 145949](https://user-images.githubusercontent.com/6453351/223719739-f741d005-59b8-4a20-87d5-83a7dea19756.png)

It says the next version is `Version20180801094926`, but I have version `20180801094926` in my database...

![Screenshot 2023-03-08 150018](https://user-images.githubusercontent.com/6453351/223719843-323ef816-7543-49f5-b41c-5abb7da26821.png)


What gives?
